/**
 * Types for the human-in-the-loop interrupt system.
 *
 * When an agent's configured tool-name glob matches a pending call, the
 * runtime persists an {@link InterruptRequest} and pauses until an
 * operator calls `TuttiRuntime.resolveInterrupt(id, "approved" | "denied", ...)`.
 * Approval resumes execution; denial aborts the run with
 * `InterruptDeniedError`.
 *
 * Distinct from `allow_human_input` / `request_human_input` — that flow
 * lets the *agent* ask a free-text question. Interrupts gate *specific
 * tool calls* behind operator review, irrespective of what the agent
 * would ask.
 *
 * @module
 */

/** Lifecycle status of a single interrupt request. */
export type InterruptStatus = "pending" | "approved" | "denied";

/** Persisted record of one interrupt request. */
export interface InterruptRequest {
  /**
   * Stable identifier — generated by the store on create (the codebase
   * uses `randomUUID` from `node:crypto` for this class of id; the spec
   * mentioned nanoid but we follow the existing convention).
   */
  interrupt_id: string;
  /** Session the request belongs to. Inherited from the active run. */
  session_id: string;
  /** Name of the tool the agent wants to call. */
  tool_name: string;
  /** Validated tool arguments at the time of the request. Stored verbatim. */
  tool_args: unknown;
  /** Wall-clock time the request was created. */
  requested_at: Date;
  /** Current lifecycle status — see {@link InterruptStatus}. */
  status: InterruptStatus;
  /** Set when the request transitions out of `"pending"`. */
  resolved_at?: Date;
  /** Optional metadata — who approved/denied (email, role, internal id). */
  resolved_by?: string;
  /** Free-text reason, populated when `status === "denied"`. */
  denial_reason?: string;
}

/**
 * Input accepted by {@link InterruptStore.create}. The store assigns
 * `interrupt_id`, `requested_at`, and `status: "pending"`.
 */
export interface InterruptCreateInput {
  session_id: string;
  tool_name: string;
  tool_args: unknown;
}

/**
 * Optional fields accepted by {@link InterruptStore.resolve}. Both are
 * recorded verbatim — backends do not enforce that `denial_reason` is
 * only set on `"denied"` resolutions or that `resolved_by` is a valid
 * identifier.
 */
export interface ResolveOptions {
  resolved_by?: string;
  denial_reason?: string;
}
