/**
 * User memory — cross-session facts an agent retains *about an end user*
 * (preferences, prior context, profile data). Distinct from semantic
 * memory ({@link MemoryEntry}), which is keyed by `agent_name` and
 * shared across all users; user memories are keyed by `user_id` and
 * isolated per end-user.
 *
 * Design-only module — these types describe the contract the runtime
 * will use once user memory ships. No backend implementations live in
 * this directory yet.
 *
 * @module
 */

import type { AgentUserMemoryConfig } from "@tuttiai/types";

/**
 * Where a memory came from. Drives both UI badging in Studio and the
 * LLM's "trust" cue when memories are injected into the system prompt.
 *
 * - `"explicit"` — the user said "remember that I prefer X" (or an
 *   equivalent intent surfaced via the API). Always attributable to a
 *   user action.
 * - `"inferred"` — the framework extracted the memory from the
 *   conversation. Lower default trust; flagged in the system-prompt
 *   render so the agent can ask for confirmation before acting.
 */
export type UserMemorySource = "explicit" | "inferred";

/**
 * Retrieval-rank weight. Higher importance ⇒ surfaced first by
 * {@link UserMemoryStore.search} and more likely to make the
 * `inject_limit` cut at run start.
 *
 * - `1` — low (background trivia, weak preferences)
 * - `2` — normal (default for most stored memories)
 * - `3` — high (hard constraints — "always reply in French", "never
 *   call this tool")
 */
export type UserMemoryImportance = 1 | 2 | 3;

/**
 * One persisted user memory.
 *
 * `id` is generated by the store (typically nanoid). `created_at` is
 * set at insert. `last_accessed_at` is updated whenever the memory is
 * surfaced via {@link UserMemoryStore.search} or
 * {@link UserMemoryStore.get} — used to drive recency-aware eviction
 * when `max_memories_per_user` is exceeded.
 */
export interface UserMemory {
  /** Stable identifier — generated by the store on insert (typically nanoid). */
  id: string;
  /** The end user this memory belongs to. Opaque to the runtime — the application chooses the namespace. */
  user_id: string;
  /** The memory text. Natural language, agent-readable; injected verbatim into the system prompt. */
  content: string;
  /** Where the memory came from — see {@link UserMemorySource}. */
  source: UserMemorySource;
  /** Retrieval-rank weight — see {@link UserMemoryImportance}. */
  importance: UserMemoryImportance;
  /** Optional categorisation tags — e.g. `["preferences", "code-style"]`. Used for filtered search and Studio grouping. */
  tags?: string[];
  /** Wall-clock time the memory was first stored. */
  created_at: Date;
  /** Wall-clock time the memory was last surfaced via search/get. Drives recency-based eviction. */
  last_accessed_at?: Date;
  /** Wall-clock time after which the memory should be purged. Absent ⇒ never expires. */
  expires_at?: Date;
}

/**
 * Optional fields accepted by {@link UserMemoryStore.store}. Every field
 * is optional — the store applies sensible defaults when omitted:
 *
 * - `source` ⇒ `"explicit"` (the safer assumption for any direct API call)
 * - `importance` ⇒ `2` (normal)
 * - `tags` ⇒ `[]`
 * - `expires_at` ⇒ `undefined` (never expires)
 */
export interface StoreOptions {
  source?: UserMemorySource;
  importance?: UserMemoryImportance;
  tags?: string[];
  expires_at?: Date;
}

/**
 * Pluggable user-memory backend. Implementations include
 * `InMemoryUserMemoryStore` (ephemeral, dev) and
 * `PostgresUserMemoryStore` (persistent, prod) — neither is implemented
 * yet; this interface defines the contract.
 *
 * Method semantics:
 *
 * - `store` — insert a new memory, returning the persisted record with
 *   `id` and `created_at` filled in by the backend. Idempotency is the
 *   *caller's* responsibility; stores do not deduplicate by content.
 * - `search` — relevance-ranked retrieval. Implementations may use
 *   keyword overlap (in-memory), full-text indexes (Postgres), or
 *   embeddings (future). `limit` defaults to 10 and matches the
 *   `inject_limit` setting in {@link AgentUserMemoryConfig}.
 * - `list` — return every memory for a user, in stable order (typically
 *   `created_at DESC`). For UIs and admin tools — not for hot-path
 *   retrieval.
 * - `delete` / `deleteAll` — hard-delete; no soft-delete in v1.
 * - `get` — direct lookup by id; returns `null` (not throws) when
 *   missing so callers can distinguish absence from error.
 *
 * Implementations MUST NOT throw on `delete` / `deleteAll` for unknown
 * ids — they should silently no-op so callers can use them as cleanup
 * primitives without having to first check existence.
 */
export interface UserMemoryStore {
  /**
   * Persist a new memory for `user_id`. Returns the stored record with
   * generated `id` and `created_at`.
   *
   * @param user_id - End-user namespace.
   * @param content - The memory text. Stored verbatim.
   * @param options - Optional metadata — see {@link StoreOptions}.
   */
  store(
    user_id: string,
    content: string,
    options?: StoreOptions,
  ): Promise<UserMemory>;

  /**
   * Return up to `limit` memories most relevant to `query` for
   * `user_id`, ordered most-relevant-first. The store should bump
   * `last_accessed_at` on every returned record.
   *
   * @param user_id - End-user namespace.
   * @param query - Free-text query — typically the current user input.
   * @param limit - Maximum results. Defaults to 10 to match the
   *   {@link AgentUserMemoryConfig.inject_limit} default.
   */
  search(
    user_id: string,
    query: string,
    limit?: number,
  ): Promise<UserMemory[]>;

  /**
   * Return every memory for `user_id` in stable order (typically
   * `created_at DESC`). Intended for admin / UI flows; hot-path code
   * should call {@link search}.
   */
  list(user_id: string): Promise<UserMemory[]>;

  /**
   * Hard-delete a single memory by id. No-op when the id is unknown —
   * idempotent on purpose so callers can treat this as a cleanup
   * primitive.
   */
  delete(id: string): Promise<void>;

  /**
   * Hard-delete every memory for `user_id`. No-op when the user has no
   * memories. Used for "forget me" / GDPR right-to-erasure flows.
   */
  deleteAll(user_id: string): Promise<void>;

  /**
   * Direct lookup by id. Returns `null` when the id is unknown so
   * callers can distinguish absence from error. Implementations should
   * bump `last_accessed_at` on a hit.
   */
  get(id: string): Promise<UserMemory | null>;
}

/**
 * Options accepted by `AgentRunner.run()` and `TuttiRuntime.run()`.
 *
 * Today both functions take positional args (`agent_name, input,
 * session_id?`). This interface is the proposed migration target — once
 * shipped, callers can pass `{ session_id, user_id }` as a single bag
 * and the positional `session_id` argument becomes deprecated.
 *
 * `user_id` is the only *new* field. When set, the runtime fetches
 * memories for that user from the configured {@link UserMemoryStore}
 * (per {@link AgentUserMemoryConfig}) and injects up to `inject_limit`
 * of them into the system prompt at run start. When absent the run is
 * anonymous — no user memories are read or written.
 *
 * Design-only — no implementation yet. The runtime does not currently
 * accept this options bag.
 */
export interface AgentRunOptions {
  /** Continue an existing session. Same semantics as today's positional `session_id`. */
  session_id?: string;
  /**
   * End-user identity. Triggers user-memory fetch + inject at run
   * start, and (when `auto_infer` is enabled) the post-run extraction
   * pass. The runtime treats this string as opaque — applications
   * choose the namespace (email, internal id, anonymous cookie hash).
   */
  user_id?: string;
}

// Re-export the agent-level config from @tuttiai/types so consumers
// working in @tuttiai/core have a single import site for everything
// user-memory-related.
export type { AgentUserMemoryConfig };
