/**
 * The kind of work a span represents. Drives both UI grouping in the Studio
 * and which {@link TuttiSpanAttributes} fields are expected to be populated.
 */
export type SpanKind = "agent" | "tool" | "llm" | "guardrail" | "checkpoint";

/**
 * Lifecycle status of a span.
 *
 * - `running` — span has been opened but not yet closed.
 * - `ok` — span closed successfully.
 * - `error` — span closed with a failure; see {@link TuttiSpan.error}.
 */
export type SpanStatus = "running" | "ok" | "error";

/**
 * Outcome of a guardrail evaluation. Recorded on guardrail spans so the
 * Studio can render policy decisions alongside the agent timeline.
 */
export type GuardrailAction = "pass" | "redact" | "block";

/**
 * Structured error captured when a span ends with `status: 'error'`.
 *
 * Keep this minimal — full stack traces leak filesystem paths and should
 * be redacted before being persisted or sent to remote sinks.
 */
export interface TuttiSpanError {
  /** Human-readable error message. Already redacted by the runtime. */
  message: string;
  /** Optional stack trace. Omit in production sinks. */
  stack?: string;
}

/**
 * Typed bag of attributes a span may carry. All fields are optional — a
 * span only populates the subset relevant to its {@link SpanKind}.
 *
 * The schema is open-typed by kind rather than discriminated so a single
 * span can carry attributes from multiple categories (e.g. a tool span
 * that also recorded a cost estimate).
 */
export interface TuttiSpanAttributes {
  // ---------------------------------------------------------------- agent
  /** Agent identifier from the score (e.g. `"assistant"`). */
  agent_id?: string;
  /** Session ID for the in-progress conversation. */
  session_id?: string;
  /** Model identifier the agent ran against (e.g. `"claude-opus-4-6"`). */
  model?: string;

  // ------------------------------------------------------------------ llm
  /** Tokens consumed by the prompt portion of an LLM call. */
  prompt_tokens?: number;
  /** Tokens generated by the model. */
  completion_tokens?: number;
  /** `prompt_tokens + completion_tokens`. Stored for convenience. */
  total_tokens?: number;
  /** Estimated cost of the LLM call in USD. */
  cost_usd?: number;

  // ---------------------------------------------------------------- router
  /**
   * Tier the `@tuttiai/router` `SmartProvider` selected for this LLM call
   * (`small` / `medium` / `large` / `fallback`). Set when the runner is
   * driving a smart router; absent otherwise.
   */
  router_tier?: string;
  /** Model the chosen tier mapped to. Mirrors `model` for non-router runs. */
  router_model?: string;
  /** Classifier strategy that picked the tier (`heuristic`, `llm`, `embedding`). */
  router_classifier?: string;
  /** Why the tier was chosen (`classified`, `forced`, `fallback after error: …`). */
  router_reason?: string;
  /** Per-call cost estimate (USD) the router computed when picking the tier. */
  router_cost_estimate?: number;
  /** Original tier's model when a fallback fired during this call. */
  router_fallback_from?: string;
  /** Fallback tier's model that handled the call after the primary threw. */
  router_fallback_to?: string;
  /** Error message that triggered the fallback. */
  router_fallback_error?: string;

  // ----------------------------------------------------------------- tool
  /** Snake-case tool name (e.g. `"read_file"`). */
  tool_name?: string;
  /** Validated tool input. May be redacted before persistence. */
  tool_input?: unknown;
  /** Tool result payload. May be truncated by the runtime. */
  tool_output?: unknown;

  // ------------------------------------------------------------ guardrail
  /** Name of the guardrail policy that produced this span. */
  guardrail_name?: string;
  /** Action taken by the guardrail. */
  guardrail_action?: GuardrailAction;
}

/**
 * A single unit of timed work captured during an agent run.
 *
 * Spans share a `trace_id` for the duration of one logical agent
 * invocation, and link to their parent through `parent_span_id` to form
 * a tree the Studio can render as a flame graph.
 *
 * Spans are mutable while running — the tracer fills in `ended_at`,
 * `duration_ms`, `status`, and any `error` when {@link TuttiTracer.endSpan}
 * is called.
 */
export interface TuttiSpan {
  /** Unique span identifier within a process. */
  span_id: string;
  /** Trace identifier shared by every span in one agent run. */
  trace_id: string;
  /** Parent span this work was nested inside, if any. */
  parent_span_id?: string;
  /** Short, dotted name (e.g. `"agent.run"`, `"tool.call"`). */
  name: string;
  /** What kind of work the span represents. */
  kind: SpanKind;
  /** Wall-clock time the span was opened. */
  started_at: Date;
  /** Wall-clock time the span was closed. Unset while running. */
  ended_at?: Date;
  /** `ended_at - started_at` in milliseconds. Unset while running. */
  duration_ms?: number;
  /** Lifecycle status — see {@link SpanStatus}. */
  status: SpanStatus;
  /** Kind-specific attributes — see {@link TuttiSpanAttributes}. */
  attributes: TuttiSpanAttributes;
  /** Populated when the span closes with `status: 'error'`. */
  error?: TuttiSpanError;
}
